repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(ts|js)$
        types: [file]
        additional_dependencies:
          - eslint@7.12.1
          - eslint-config-airbnb-base@14.1.0
          - eslint-config-prettier@6.15.0
          - eslint-plugin-import@2.22.1
          - eslint-plugin-prettier@3.1.2
          - "@typescript-eslint/eslint-plugin@6.1.0"
          - "@typescript-eslint/parser@6.1.0"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [json, yaml, markdown]
